In [1]:
import numpy as np

1.

In [2]:
a1 = np.random.randint(0, 9, (5, 5))
a1

array([[4, 7, 5, 0, 8],
       [5, 5, 2, 1, 1],
       [5, 1, 7, 4, 0],
       [6, 6, 6, 3, 5],
       [7, 8, 2, 8, 5]])

In [3]:
a1_t = np.transpose(a1)
a1_t

array([[4, 5, 5, 6, 7],
       [7, 5, 1, 6, 8],
       [5, 2, 7, 6, 2],
       [0, 1, 4, 3, 8],
       [8, 1, 0, 5, 5]])

In [4]:
a1_inv = np.linalg.inv(a1)
a1_inv

array([[ -7.68292683,  -2.43902439,  -6.08943089,  15.08943089,
         -2.30894309],
       [  6.75609756,   2.41463415,   5.32520325, -13.32520325,
          2.03252033],
       [  3.56097561,   1.14634146,   2.91869919,  -6.91869919,
          0.99186992],
       [  1.68292683,   0.43902439,   1.42276423,  -3.42276423,
          0.64227642],
       [ -4.17073171,  -1.6097561 ,  -3.43902439,   8.43902439,
         -1.24390244]])

In [5]:
a2 = np.eye(4)*np.random.randint(0, 9, (4, 4))
a2

array([[2., 0., 0., 0.],
       [0., 2., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 7.]])

In [6]:
a3 = np.zeros((3, 3))
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

2.

In [7]:
print('Определитель a1 = ', round(np.linalg.det(a1)))
print('Определитель a1_t = ', round(np.linalg.det(a1_t)))
print('Определитель a1_inv = ', np.linalg.det(a1_inv))
print('Определитель a2 = ', round(np.linalg.det(a2)))
print('Определитель a3 = ', round(np.linalg.det(a3)))

Определитель a1 =  123
Определитель a1_t =  123
Определитель a1_inv =  0.008130081300812976
Определитель a2 =  0
Определитель a3 =  0


In [8]:
print(-822**-1) #определитель обратной матрицы - определитель матрицы в -1 степени
2*4*8*2 #определитель диагональной - произведению элементов главной диагонали

-0.0012165450121654502


128

In [9]:
print('Ранг a1 = ', np.linalg.matrix_rank(a1))
print('Ранг a1_t = ', np.linalg.matrix_rank(a1_t))
print('Ранг a1_inv = ', np.linalg.matrix_rank(a1_inv))
print('Ранг a2 = ', np.linalg.matrix_rank(a2))
print('Ранг a3 = ', np.linalg.matrix_rank(a3))

Ранг a1 =  5
Ранг a1_t =  5
Ранг a1_inv =  5
Ранг a2 =  3
Ранг a3 =  0


In [10]:
np.linalg.eigvals(a1)

array([21.42447937, -4.65258219, -0.13106728,  1.64866263,  5.71050746])

In [11]:
np.linalg.eigvals(a1_t)

array([21.42447937, -4.65258219,  5.71050746, -0.13106728,  1.64866263])

In [12]:
np.linalg.eigvals(a1_inv)

array([-7.62966935,  0.60655223, -0.21493441,  0.04667558,  0.17511579])

In [13]:
np.linalg.eigvals(a2)

array([2., 2., 0., 7.])

In [14]:
np.linalg.eigvals(a3)

array([0., 0., 0.])